version: "3.6"
services:
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha38
    restart: always
    container_name: engine
    environment:
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS512","jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"}'
      HASURA_GRAPHQL_ENDPOINT_EDITORIAL_WORKFLOW: http://devenv:6012/pickle-platform/us-central1/editorialWorkflow
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:bq1kbqa269uBp3b0@35.246.253.22:5432/ehaber_staging
      HASURA_GRAPHQL_ACCESS_KEY: 'b!tchdontk1llMYvibestaging2014'
    networks:
      main:
        aliases:
          - graphql-engine
    command:
      - graphql-engine
      - serve
  devenv:
    image: noddigital/pickle-devenv
    container_name: devenv
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: always
    networks:
      main:
        aliases:
          - devenv
    ports:
      - "6000:6000" # sshd
      - "6001:5000" # micro proxy
      - "6002:5000" # storybook
      - "6003:5000" # hasura console
      - "6010:3011" # dashboard
      - "6011:3010" # ehaber-web
      - "6012:5000" # functions-dev
      - "9005:9005" # firebase login
    volumes:
      - firebase-config:/root/.config
      - ./authorized_keys:/root/.ssh/authorized_keys
      - ../:/root/pickle-main:cached

networks:
  main:

volumes:
  firebase-config:
